### PR TITLE
libdecor patches for MC 1.19

### PR DESCRIPTION
**Pull request by markx86**
Adds patches for libdecor support in GLFW (commit `62e175ef9fae75335575964c845a302447c012c7`).

### CODE REVIEW

**Comment by Admicos** [comment]
I'm getting an `xdg_surface@20: error 3: xdg_surface has never been configured` error under Weston with this.

**Comment by VolatileMark** [comment]
Sorry, it took a while to track down the problem, but it should be fixed now!

**Comment by Admicos** [comment]
resizing is a bit laggy (although that could just be an issue on my end), but looks good to me

not merging the pr yet because i'm planning to do re-organize the repo soon, but otherwise this seems ready

**Comment by VolatileMark** [comment]
> resizing is a bit laggy
I think that's a Wayland issue with the GLFW commit that's used in the `PKGBUILD`, because it lags, when resizing, with and without the libdecor patches (at least on my system)

**Comment by orowith2os** [comment]
Is this still needed? It shouldn't be when a new GLFW release is made: https://github.com/glfw/glfw/commit/fbdb53b9ca457ab01675e20d9127cb62d8db88b8

**Comment by ChrisLane** [comment]
> Is this still needed? It shouldn't be when a new GLFW release is made: [glfw/glfw@fbdb53b](https://github.com/glfw/glfw/commit/fbdb53b9ca457ab01675e20d9127cb62d8db88b8)

Yep, this is now in [v3.3.9](https://github.com/glfw/glfw/releases/tag/3.3.9) I think so this PR can be closed.

**Pull request closed without merging**
